package com.example.retodam2rutas.model

import com.example.retodam2rutas.entities.CLASIFICACION
import com.example.retodam2rutas.entities.Ruta
import java.time.LocalTime

data class RutaModel(
    val id: Long,
    val nombre: String,
    val nombreInicioruta: String,
    val nombreFinalruta: String,
    val latitudInicial: Double,
    val latitudFinal: Double,
    val longitudInicial: Double,
    val longitudFinal: Double,
    val distancia: Double,
    val duracion: String,
    val desnivelPositivo: Int,
    val desnivelNegativo: Int,
    val desnivelAcumulado: Int,
    val altitudMax: Double,
    val altitudMin: Double,
    val clasificacion: String,
    val nivelEsfuerzo: Byte?,
    val nivelRiesgo: Byte?,
    val estadoRuta: Boolean,
    val tipoTerreno: Byte?,
    val indicaciones: Byte?,
    val temporadas: String?,
    val accesibilidad: Boolean,
    val rutaFamiliar: Boolean,
    val archivoGPX: String?,
    val recomendacionesEquipo: String?,
    val zonaGeografica: String?,
    val mediaEstrellas: Double?,
    val usuarioId: Int
)
fun RutaModel.toEntity() = Ruta(
    id = id,
    nombre = nombre,
    nombreInicioruta = nombreInicioruta,
    nombreFinalruta = nombreFinalruta,
    latitudInicial = latitudInicial,
    latitudFinal = latitudFinal,
    longitudInicial = longitudInicial,
    longitudFinal = longitudFinal,
    distancia = distancia,
    duracion = LocalTime.parse(duracion),
    desnivelPositivo = desnivelPositivo,
    desnivelNegativo = desnivelNegativo,
    desnivelAcumulado = desnivelAcumulado,
    altitudMax = altitudMax,
    altitudMin = altitudMin,
    clasificacion = CLASIFICACION.valueOf(clasificacion),
    nivelEsfuerzo = nivelEsfuerzo,
    nivelRiesgo = nivelRiesgo,
    estadoRuta = estadoRuta,
    tipoTerreno = tipoTerreno,
    indicaciones = indicaciones,
    temporadas = temporadas,
    accesibilidad = accesibilidad,
    rutaFamiliar = rutaFamiliar,
    archivoGPX = archivoGPX,
    recomendacionesEquipo = recomendacionesEquipo,
    zonaGeografica = zonaGeografica,
    mediaEstrellas = mediaEstrellas,
    usuarioId = usuarioId
)
