<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.5.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="OxyPlot.Core" Version="2.2.0" />
    <PackageReference Include="OxyPlot.WindowsForms" Version="2.2.0" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Conexion\Conexion.csproj" />
    <ProjectReference Include="..\ModeloTDO\ModeloDTO.csproj" />
    <ProjectReference Include="..\Modelo\Modelo.csproj" />
  </ItemGroup>

</Project>